dictu-lang/Dictu

.gitignore, c.make, c/chunk.h, c/collections.c, c/compiler.c, c/files.c, c/files.h, c/main.c, c/memory.c, c/object.c, c/object.h, c/strings.c, c/value.h, c/vm.c, docs/docs/files.md
Resolves #20 
This PR allows you to work with files in Dictu. It exposes 5 new methods, and the file object into Dictu.
- read()
- readLine()
- write()
- writeLine()
- seek()
More information included in the documentation.
=> Ability to work with files in Dictu

c/collections.c, c/collections.h, c/common.h, c/files.c, c/memory.c, c/memory.h, c/natives.c, c/object.c, c/object.h, c/strings.c, c/value.c, c/value.h, c/vm.c, c/vm.h, tests/lists/copy.du, tests/runTests.du, tests/strings/split.du
- This PR aims to get both lists and dictionaries working correctly with the garbage collector. In Dictu's current state, the GC seems to clean lists before they should be cleaned, and dictionaries are not implemented yet.
=> Slight cleanup

c/strings.c, docs/docs/strings.md, tests/strings/count.du, tests/strings/import.du
Ability to count substrings within a string
```
"Dictu is great!".count("Dictu"); // 1
"Sooooooooooome characters".count("o"); // 11
```
=> Add str.count()

c/datatypes/dicts.c, c/main.c, c/value.c, c/vm.c, c/vm.h, docs/_config.yml
This release is quite small, however, there has been no "official" release tagged here on github, and this issue marked the last for what i wanted to be completed for a "proper" release.
- Dynamically grow CallFrames within the VM when required #88
=> Release 0.2.0

README.md, examples/classes.du, examples/factorial.du, examples/fizzBuzz.du, examples/recursiveFib.du
Resolves #104 
Adds more example Dictu programs to the repository.
=> Example programs

docs/docs/built-ins.md, docs/docs/files.md, docs/docs/math.md
The previous PR (#123) was merged without having the proper documentation in place for the changed builtin / Math functions, this PR resolves that issue.
=> Add missing documentation for Math class

docs/docs/built-ins.md, docs/docs/classes.md, docs/docs/collections.md, docs/docs/env.md, docs/docs/files.md, docs/docs/json.md, docs/docs/math.md, docs/docs/strings.md, docs/docs/system.md
This PR rewrites most of the documentation pages to try and keep the documentation more consistent.
=> Rework documentation

.github/workflows/main.yml, c.make, c/optionals/http.c, c/optionals/http.h, c/optionals/optionals.h, c/vm.c, docs/docs/http.md, tests/http/get.du, tests/http/import.du, tests/http/post.du, tests/runTests.du
This PR brings a new native HTTP class to Dictu! This new class will allow us to (for now) do GET and POST requests to HTTP/HTTPS endpoints! This is done via the use of [libcurl](https://curl.haxx.se/libcurl/). Eventually libcurl should be swapped out when Dictu has the ability to work with scokets, and the HTTP implementation can be created with the Dictu socket library.
```
>>> HTTP.get("http://httpbin.org/get");
{"content": '{
"args": {},
"headers": {
"Accept": "*/*",
"Host": "httpbin.org",
"X-Amzn-Trace-Id": "Root=1-5e542774-69951dd0a1ee0ae38d13c0f4"
},
"origin": "...",
"url": "http://httpbin.org/get"
}
', "headers": ['HTTP/1.1 200 OK', 'Date: Mon, 24 Feb 2020 19:43:48 GMT', 'Content-Type: application/json', 'Content-Length: 219', 'Connection: keep-alive', 'Server: gunicorn/19.9.0', …
```
=> HTTP Support

c.make, c/compiler.c, c/memory.c, c/scanner.c
Add -Wshadow -Wunused-function -Wunused-macros to the CFLAGS and fix a couple of warnings.
=> Add warnings and fix -Wshadow-warnings.

c/compiler.c, docs/docs/variables.md, tests/variables/assignment.du
Resolves #149 
This PR adds the ability to define multiple variables in a single statement.
```js
var a, b = 10, c = "hello!";
print(a, b, c); // nil, 10, 'hello!'
```
=> Multiple assignment

c/optionals/optionals.h, c/optionals/path.c, c/optionals/path.h, c/vm.c, docs/docs/env.md, docs/docs/http.md, docs/docs/json.md, docs/docs/path.md, docs/docs/system.md, tests/path/path.du, tests/runTests.du
=> Add Path Native class.

c/datatypes/bool.c, c/datatypes/bool.h, c/datatypes/nil.c, c/datatypes/nil.h, c/datatypes/number.c, c/datatypes/number.h, c/memory.c, c/vm.c, c/vm.h
This PR adds the scaffolding for more native values on booleans, numbers and nil. This will compliment #183 which is currently open, in the transition from a native builtin to methods on values.
=> Native methods

c/scanner.c
=> Add 'not' keyword.

c/optionals/system.c, c/optionals/system.h, docs/docs/system.md, tests/system/import.du, tests/system/remove.du
Returns 0 upon success and -1 otherwise.
=> Add System.remove() method, that deletes a file from the filesystem.

c/optionals/system.c, c/optionals/system.h, docs/docs/system.md, tests/system/mkdir.du
Both return 0 upon success and -1 otherwise.
System.mkdir() can take an optional number argument that specifies the mode.
Add also S_I* constants to specify the permissions bits.
=> Add System.mkdir() and System.rmdir().

c/optionals/system.c, docs/docs/system.md, tests/system/import.du, tests/system/mkdir.du, tests/system/process.du, tests/system/remove.du
These functions should always return succesfully.
=> Add System.[getpid(),getppid(),getuid(),geteuid(),getgid(),getegid()]

README.md, examples/factorial.du, examples/guessingGame.du
Reolves #210 
Some of the example programs were outdated and needed updating to the new syntax. This PR does this.
=> Update example programs

docs/docs/files.md, tests/files/import.du, tests/files/read.du, tests/files/seek.du, tests/files/write.du, tests/files/writeLine.du
This PR updates the file documentation to be more precise in certain areas and add some missing information (such as file opening modes), and it also adds tests regarding files.
=> File documentation

docs/docs/env.md, docs/docs/path.md, docs/docs/system.md, tests/classes/copy.du, tests/dicts/copy.du, tests/lists/copy.du
Add some more tests for copying dicts / lists / instances. Also fix documentation.
=> Add some more tests and fix documentation

c/vm.c
This PR aims to simplify some VM opcodes. `SUBSCRIPT_ASSIGN` was peeking the VM for it's required 3 values, however this opcode should never cause a GC as it's not inserting a new item into a list / dictionary, it's only ever updating a value that exists already.
`PUSH` popped 3 values off the stack to then push them on in a slightly different order, however instead of doing this we can leave the values on the stack and just update the top value of the stack and push the extra value it needs simplifying the process ever so slightly.
`OPEN_FILE` had a bug where it was popping the filename and the file open type off the stack however it uses these values after `initFile()`. `initFile()` creates a new object, which therefore means a GC could happen, and if nothing references the filename, or …
=> Simplify some VM opcodes and fix issue with files

examples/README.md, examples/fizzBuzz.du, examples/guessingGame.du
Create a README document within the examples directory to give a quick overview of the included example files. Reason being is it allows you to see a range of example files without having to click and view each one.
=> Create examples readme

c/datatypes/lists.c, docs/docs/collections.md, tests/lists/import.du, tests/lists/remove.du
This PR adds `.remove()` to lists, that will remove a given value from a list. A call to this method will only remove the first occurrence of the value, and not all (if there are multiple of the same).
=> Add list.remove()

examples/design-patterns/README.md, examples/design-patterns/builder.du, examples/design-patterns/chain-of-responsibility.du, examples/design-patterns/observer.du
This PR adds some example design patterns written in Dictu, to hopefully help people who have an OOP language background understand how known patterns would be implemented in Dictu.
=> Add some OOP design patterns written in Dictu.

c/datatypes/strings.c, c/optionals/socket.c, c/vm.c
While writing some Dictu applications i'd discovered it was segfaulting. From tracing the error, i found a few places throughout the code in which a memory issue could occur if the conditions were right. This PR fixes these issues.
=> Fix memory issues

c/datatypes/lists.c, docs/docs/collections.md, tests/lists/import.du, tests/lists/sort.du
Implement list sorting for numbers as in #264 
Resolves #264 
Changes
-----------
1. Added list sorting for numbers, with quick sort (Hoare partition method) being the sorting algorithm.
2. Added relevant tests.
Details
--------
The sorting algorithm is Quick Sort (Hoare partition scheme). The average complexity is O( n log (n) ) and the worst case complexity is O( n^ 2 ) (albeit in rare cases).
Further Improvement
------------------------
Quick sort is a bit overkill for small lists, we could use some simpler algorithm instead for list sizes less than 20 maybe.
=> Implement list sorting for numbers.

c/optionals/path.c, docs/docs/path.md, tests/path/import.du, tests/path/isdir.du
Hi I made a pr for #259 
@Jason2605 Please let me know if more changes are necessary, I'll try to come with a windows implementation too if you wish.
=> Adding isdir()

c/optionals/optionals.c, c/optionals/optionals.h, c/optionals/random.c, c/optionals/random.h, docs/docs/random.md, docs/docs/sockets.md, tests/random/import.du, tests/random/random.du, tests/random/range.du, tests/random/select.du
Feature for #273. 
Still need to add `Random.range()` and `Random.select()`, but that will be done fairly quickly. 
Dictu tests are also added.
There is also a FIXME in here where I'm unsure how to surpress `-Werror` for not using a function parameter. I don't see any examples in the already existing code so I'm unsure how to cleanly get around this.
=> Implement Random

c/optionals/path.c, c/optionals/path.h, docs/docs/path.md, tests/path/listdir.du
=> Add Path.listdir() method

c/datatypes/strings.c, docs/docs/strings.md, tests/strings/split.du
PR for #280 
added functionality to split string into individual characters if empty string is passed as delimiters
=> add string.split function for empty string delimiters

c/optionals/math.c, docs/docs/math.md, tests/maths/maths.du
Previous commit  adb786eda9a1ca5fe33676a02ff5d74a8f04f77f, that was failing because of wrong assertions. Those were fixed in this latest commit.
=> Implemented sin, cos, tan in math package.

c/scanner.c, tests/number/import.du, tests/number/literals.du
Now language supports hex values and  exponents 
ex:
0xA2F , 0XA2F , 0xa2f , 0Xa2f
1e3,1e+5,1e-5,etc
=> feature/Hexadecimal and Exponents numbers

examples/isPalindrome.du
=> feat(examples): add isPalindrome.du

examples/inheritance.du
Added an example for inheritance
=> Added example for inheritance

examples/design-patterns/factoryMethod.du
Hi, I have added factory method design pattern . Happy coding
=> Added Example for Design pattern - Factory method

examples/bubbleSort.du
=> add bubble sort example

c/compiler.c, c/vm.c, tests/modules/functions.du, tests/modules/variables.du
Resolves #297 
This PR fixes an issue where importing into a local scope was not working as intended. It also adds some test scenarios to ensure this issue does not regress in the future.
=> Fix nested imports

.dockerignore, Docker/DictuUbuntuDockerfile, Docker/README.md, README.md
- Added the ubuntu image of Dictu
- Will open an issue for the alpine image
=> Added docker installation of Dictu

examples/binarySearchTree.du
Adding example for insert and search operations of Binary Search Tree.
Addresses issue #277
=> feat(examples): add binarySearchTree.du

Docker/DictuUbuntuDockerfile
Tests are run before the Docker image build is completed.
=> Added test run in Docker build

Docker/DictuAlpineDockerfile, Docker/README.md
- Added the Dockerfile for *alpine* as the base image and compiled dictu with HTTP.
- Updated the Docker docs for the same.
=> Added Dockerfile for alpine dictu

c/datatypes/instance.c, docs/docs/classes.md, tests/classes/import.du, tests/classes/isInstance.du
Resolves #306 
This PR adds a new `isInstance` method to object instances. This allows us to check if a given object was created by a given class. As explained in the documentation, if the instance being checked was instantiated from an inherited class, `isInstance` will evaluate to true if a parent class is passed in.
=> obj.isInstance

src/vm/compiler.c
Resolves #344 
Break statements work by retrospectively looking through a chunks bytecode and replacing an `OP_BREAK` with an `OP_JUMP`. This in principle is a fine design, however the way it was implemented - not so much. Essentially it was checking both the opcodes and the operands for the given instruction which would end up giving false positives for the condition and re-writing bytecode that shouldn't have been changed. This PR fixes this to ensure that only opcodes are compared against.
=> Ensure the correct value is being compared for OP_BREAK

src/vm/compiler.c
Resolves #383 
When shuffling the bytecode in endLoop it was indexing by the wrong value when attempting to get the function from the list of constants, this was causing the function to be null and then caused a segfault when trying to access memory. This PR resolves this by indexing with the correct value.
=> Correctly handle bytecode reshuffle for closures and import

docs/docs/classes.md
Update documentation surrounding attributes to be more correct.
=> Update attribute documentation

src/vm/vm.c
In theory this should be slightly better since in terms of performance as it's not subtracting and adding to `stackTop`. In practice i'm not sure how much gain it will actually have.
=> Potential slight optimisation

docs/docs/standard-lib/system.md, src/optionals/system.c, tests/system/import.du, tests/system/sleep.du, tests/system/time.du, tests/system/version.du
This PR adds in a a dictionary containing the Dictu version into the System module.
=> Add System.version dictionary

README.md, docs/docs/thank-you.md
Dictu has proudly been sponsored by DigitalOcean, so this PR reflects this and adds some "thank you" notes in the readme and documentation website
=> Add DO sponsorship tags

examples/fibonacci.du, examples/recursiveFib.du
This update shows off a couple additional (more efficient) ways to compute the n-th fibonacci number.
=> Update fibonacci example

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md
I created the GitHub templates needed !
It is my first hacktoberfest 2021 PR
=> GitHub Templates

.github/ISSUE_TEMPLATE/feature-report.md
I worked on the feature.md
#
- Closes #422 
#
#
=> Created Feature.md Template

docs/docs/standard-lib/path.md, src/optionals/path.c, tests/path/join.du
Closes #432
`Path.join` was added, along with tests and documentation.
#432
=> Add `Path.join`

docs/docs/standard-lib/math.md, src/optionals/math.c, src/optionals/math.h, tests/maths/maths.du
=> Add `Math.gcd` and `Math.lcm`

src/vm/datatypes/instance.c, tests/classes/getAttributes.du, tests/classes/import.du
This PR changes `obj.getAttribute()` so that it also checks the public methods associated to the object along with any class variables that are stored on the class that created the object, or any classes down the inheritance chain.
#
=> obj.getAttribute()

src/vm/vm.c
This PR essentially addresses #452 - detail is included within the issue.
#
=> Pop the value off the stack after printing and table resize

.github/workflows/main.yml, examples/factorial.du, examples/guessingGame.du, examples/runExamples.du
This PR updates the CI/CD pipeline (github actions) so that the examples are ran to ensure they are still kept up-to-date.
Resolves #447 
#
This PR slightly modifies some of the examples with user input to "mock" user input.
#
=> Update so examples run as part of the CI/CD pipeline

.github/workflows/main.yml, docs/docs/control-flow.md, docs/docs/standard-lib/math.md, docs/docs/strings.md, examples/README.md, examples/design-patterns/README.md, src/optionals/math.c, src/vm/memory.c, src/vm/vm.c, tests/maths/maths.du, tests/modules/from.du
This PR is a bit of a range of things:
- Update outdated documentation
- Make `Math.PI` `Math.pi` to be consistent with `Math.e`
- Update the debug messages for `DEBUG_TRACE_MEM` and `DEBUG_FINAL_MEM` to better reflect the memory allocation / memory lost at VM exit.
#
#
=> Range of updates

docs/docs/standard-lib/math.md, src/optionals/math.c, tests/maths/maths.du
Signed-off-by: Brian Downs <bdowns@Brians-MacBook-Pro.local>
Add additional native properties in math mod.
Resolves: 
#
#
=> add additional math mod values

tests/system/access.du, tests/system/import.du
Fixed `System.access()` tests and ensures that they're ran as part of the test suite
Related to: #493  
#
#
#
=> Fix System.access() tests

docs/docs/standard-lib/log.md, src/optionals/log.c, src/optionals/log.h, src/optionals/optionals.c, src/optionals/optionals.h, src/vm/natives.c, tests/log/import.du, tests/log/log.du, tests/runTests.du
Resolves: 
#
Adds a simple log package.
I also have a structured logger written entirely in Dictu using the JSON module. Was hoping for feedback on this and possible integration of the structured one.
#
=> initial log module impl

examples/openweathermap.du
Adds example code using the HTTP, System, Env, and JSON modules to connect to, parse, and print a response from openweathermap.org.
Resolves: #
#
#
#
=> Add openweathermap example app

docs/docs/standard-lib/http.md, scripts/generate.du, src/optionals/http/http-source.h, src/optionals/http/http.c, src/optionals/http/http.du, src/optionals/http/http.h, src/optionals/optionals.c, src/optionals/optionals.h, src/optionals/unittest/unittest-source.h, tests/http/get.du, tests/http/import.du, tests/http/post.du
This PR changes the HTTP module so that a Response object is returned rather than a dictionary. This allows us to bundle related logic about processing a HTTP request into this object (e.g massively simplifying JSON parsing).
Resolves: #511
#
#
#
=> HTTP Response

docs/docs/standard-lib/unittest.md, src/optionals/unittest/unittest-source.h, src/optionals/unittest/unittest.du
This PR adds 3 new methods to the `UnitTest` library:
- `assertNotEquals`
- `assertNil`
- `assertNotNil`
#
#
#
=> Add new helper methods to the unit test module

src/optionals/http/http.c
The headers list for the HTTP request was being pushed to the stack but not correctly popped back off
#
#
=> Ensure headers pushed to stack is correctly popped

src/optionals/log.c, src/optionals/socket.c, src/optionals/sqlite.c, src/vm/object.c, src/vm/object.h
This adds the ability to define a function so that abstracts can have a printable type rather than "unknown".
Resolves: #516 
#
#
#
=> Ability to properly print abstract types

README.md
Resolves: #506 
#
This is a documentation update rather than a bug fix as the original issue indicates however related nonetheless.
#
#
=> Update readme to include FreeBSD

docs/docs/standard-lib/system.md, examples/system.du, src/optionals/system.c, tests/system/import.du, tests/system/uname.du
Added the `uname` method to the System module as well as documentation and tests for new function. I left the `System.platform` variable for backwards compatibility.
Resolves: #533 
#
#
#
=> Add uname function to System module.

src/vm/compiler.c
Resolves an issue where functions defined within loops caused segfaults if the break keyword was used.
Resolves: #541
#
#
#
=> Fix loop issue

examples/reverse_proxy.du
=> add proxy example

docs/docs/standard-lib/env.md, src/optionals/env/env.c, src/optionals/env/env.h, tests/env/env.du
Adds a function that clears all environment variables.
Resolves: #
#
#
#
=> add Env.clearAll function

.github/workflows/main.yml, scripts/checkTests.du, tests/runTests.du, tests/term/getSize.du, tests/term/isatty.du
Script added to github actions to ensure tests are added to `runTests.du`.
=> Dirty checkTests script to ensure all test directories are imported

examples/httpClient.du, src/optionals/http/http.c
Casts timeout value as long and updates the http client example code.
Resolves: #
#
#
#
=> update http client timeout and client example

src/optionals/http/http.c, tests/http/client.du
Adds default behavior to follow redirects and adds ability to turn that behavior off on the client.
Resolves: #564 
#
#
#
=> add follow redirects to http

src/optionals/http/http.c, tests/http/constants.du
Fix status ok const name.
Resolves: #
#
#
#
=> fix status const name

docs/docs/collections/lists.md, src/vm/datatypes/lists/list-source.h, src/vm/datatypes/lists/list.du, tests/lists/import.du, tests/lists/splice.du
Splice provides a means of changing the contents of a list by removing or replacing existing elements and/or adding new elements in place.
Resolves: #
#
#
#
=> add list splice method

src/vm/compiler.c, src/vm/memory.c, src/vm/vm.c, src/vm/vm.h
Resolved an issue with annotations along with caching the string within the VM.
Resolves: #590 
#
#
@briandowns this should hopefully resolve the annotation issue
=> Resolve issue with annotations

docs/docs/standard-lib/socket.md, src/optionals/socket.c
Adds additional protocols to socket module. Primarily for working with UDP dependent servers. E.g. DNS, DHCP
Resolves: #
#
#
#
=> Extend socket module

docs/docs/files.md, src/vm/datatypes/files.c
Adds the ability to write in binary mode.
With this change, the following code works:
```cs
#!/usr/bin/env dictu
import HTTP;
import System;
{ // main
const opts = {
"timeout": 20,
"headers": [
"User-Agent: Dictu"
],
"insecure": true,
"follow-redirects": true
};
const client = HTTP.newClient(opts);
const res = client.get("https://curl.se/download/curl-7.86.0.zip");
const result = res.unwrap();
with("curl-7.86.0.zip", "wb") {
file.write(result.content);
}
System.exit(0);
}
```
Resolves: #
#567 
#
#
=> update file handling to account for writing in binary mode

.github/workflows/release.yml, ops/pkgBuild.du
Fix issue with building RPMs and pushing release assets.
Resolves: #
#
#
#
=> fix packaging build ci

docs/docs/collections/lists.md
=> Fix typo in lists.md

docs/docs/standard-lib/argparse.md, docs/docs/standard-lib/bigint.md, docs/docs/standard-lib/http.md, docs/docs/standard-lib/json.md, docs/docs/standard-lib/object.md, docs/docs/standard-lib/queue.md, docs/docs/standard-lib/socket.md
Fixes issue with the documentation where it was rendering incorrectly
#
#
#
=> Fix issue with docs

docs/docs/error-handling.md, docs/docs/standard-lib/object.md, docs/docs/standard-lib/process.md, examples/objectHash.du, examples/object_hash.du, examples/templateEngine.du, src/optionals/object/object.c, tests/object/hash.du, tests/object/import.du
=> Add hash Function to Object Module

docs/docs/operators.md, src/vm/value.c, src/vm/value.h, src/vm/vm.c, tests/operators/greater.du, tests/operators/import.du, tests/operators/less.du
Resolves: #
Adds the ability to use < and > on strings for a lex comparison
#
#
#
=> String Comparison

src/vm/value.c, tests/operators/greater.du, tests/operators/less.du
Fixes an issue with the less than and greater than operators on strings
#
#
#
=> Fix issue with string operations on less and greater than

.gitignore, docs/docs/standard-lib/stack.md, docs/docs/standard-lib/system.md, docs/docs/standard-lib/term.md, docs/docs/standard-lib/unittest.md, docs/docs/standard-lib/uuid.md, src/optionals/optionals.c, src/optionals/optionals.h, src/optionals/queue.c, src/optionals/stack.c, src/optionals/stack.h, tests/queue/queue.du, tests/runTests.du, tests/stack/import.du, tests/stack/stack.du
Add Stack Module
Resolves: #
Adds a new module that implements a stack and includes tests and docs.
- [ x ] New feature
#
#
=> Add stack module

ops/buildAndInstallLatest.du
Resolves: #
This script is helpful for when new code is merged to develop. It will pull the updates down, build them, and install the new binary.
#
#
=> Add pull, build, install script

src/vm/memory.c
Resolves: #
Ensure annotations are greyed
#
#
#
=> Ensure annotations are greyed

docs/docs/standard-lib/http.md, src/optionals/http/http.c
Touched: #663 
Adds a new .put() method to the HTTP lib for PUT requests
#
#
#
=> Add put requests

ops/buildAndInstallLatest.du
Adds the ability to build in debug to the buildAndInstall script.
- [ X ] New feature
#
#
=> add ability to build in debug

docs/docs/standard-lib/http.md, src/optionals/http/http.c, tests/http/clientHead.du, tests/http/head.du, tests/http/import.du
Adds the ability to send and process HTTP HEAD requests.
- [ X ] New feature
#
- [ X ] Tests have been updated to reflect the changes done within this PR (if applicable).
- [ X ] Documentation has been updated to reflect the changes done within this PR (if applicable).
#
=> Add http head requests

docs/docs/classes.md, src/vm/compiler.c, tests/classes/annotations.du
Resolves: #685 
Allows both lists and dictionaries to be used within annotations
#
#
#
=> Annotation Values

src/cli/main.c
=> Initial support for dictu path and relocate history

docs/docs/standard-lib/system.md, src/optionals/system.c, tests/system/import.du, tests/system/rename.du
Add rename, tests, and docs.
#
#
=> Add rename, tests, and docs
