dictu-lang/Dictu

c/vm.c
Resolves #7 
Currently within the str() function the length of the string is calculated via `snprintf`, and one is added to the length, this however causes an issue as the `copyString` function is not expecting this extra character therefore creating a string which is perceived as different.
=> Fix str() function

c/scanner.c
Fixed implicit fall-through in switch..case. This doesn't fix a bug, but makes it possible to compile with `-Werror`
=> Fixed implicit fallthrough in switch case

c/memory.c, c/value.c, c/vm.c, c/vm.h
Resolves #17 
This PR grants the ability to directly compare lists with lists, and dictionaries with dictionaries with the standard `==` operation.
e.g
```
[] == []; // true
["test", 1, nil] == ["test", 1, nil]; // true
[] == [nil]; // false
{"hello": 10} == {"hello": 10}; // true
{"hi": 2} == {"hi": 10} // false
```
This PR also fixes an issue with the repl variable.
=> Comparisons between dicts and lists

c/collections.c, c/object.c, c/strings.c, c/strings.h, c/vm.c, docs/docs/built-ins.md, docs/docs/classes.md, docs/docs/collections.md, docs/docs/control-flow.md, docs/docs/operators.md, docs/docs/strings.md
Resolves #6 
Currently, there are no methods which allow you to manipulate strings in Dictu. This PR changes this by adding 11 methods which allow basic string functionality.
```
.lower()
.upper()
.startsWith()
.endsWith()
.split()
.replace()
.contains()
.find()
.leftStrip()
.rightStrip()
.strip()
```
Information about each method is included in the Docs.
=> Implement string methods

c/vm.c
Resolves #21 
Currently when a runtime error is thrown the stack is not being reset, this is causing errors to stack up and duplicate (see #21). This PR fixes this issue by resetting the stack when a runtime error takes place.
=> Call resetStack on a runtime error

c.make, c/compiler.c, c/object.h, c/strings.c, c/vm.c
Resolves #24 #25 
Currently native functions segfault on a runtime error. This is due to the stack being reset, however operations were still being done as if it was not reset. This is resolved by exiting out if a runtime error occurs. This PR also adds some more error checking on native functions.
str.replace() had either unexpected results, or was also segfaulting. This seemed to be an issue with the evil `strncpy` which has now been swapped for `snprintf`.
=> Fix native functions segfault on runtimeError and fix str.replace()

c/collections.c, c/value.c, docs/docs/collections.md, tests/dicts/copy.du, tests/dicts/import.du, tests/lists/copy.du, tests/lists/import.du
Currently there is no way to make a copy of lists and dictionaries. Due to them being mutable taking a reference will mutate the original list. This PR changes this by implementing the ability to copy them.
```js
var x = [1, 2, [3, 4]];
var y = x.copy(); // Shallow copy
var z = x.deepCopy(); // Deep copy
```
```js
var x = {"key": {"key1": 10}};
var y = x.copy(); // Shallow copy
var z = x.deepCopy(); // Deep copy
```
Documentation has also been updated to explain the two new functions.
Tests created for copy() and deepCopy().
=> Implement the ability to copy mutable datatypes

Makefile
Update makefile for debug builds.
Copies the interpreter to the top level like `make dictu` does.
=> Update makefile for debug builds

c/object.h, c/vm.c
The invoke method is used to invoke methods on different types of variable. For example there may be a method on an instance, or a function on a string. In its current state this was determined via an if-elseif chain, which could require multiple branch conditions to be evaluated before finally arriving at the correct statement. This PR changes this by returning the object type, and switching on this type instead.
=> Slight optimisation for invoke method

c/object.c
Currently printing large lists causes a segfault, this is obviously not ideal 😄 This PR fixes this by removing the strncat functions and replacing it for snprintf for string concatenation.
Resolves #57
=> Fix printing lists and dictionaries

c/collections.c, c/compiler.c, c/memory.c, c/natives.c, c/object.c, c/object.h, c/strings.c, c/vm.c, c/vm.h, tests/operators/equality.du, tests/operators/import.du
This PR was intended to begin to introduce some escape codes into Dictu (\n, \t, ..) however it became apparent that there was a slight issue with some methods. After attempting to complete the [Advent of code](https://adventofcode.com/) challenge in Dictu, it was clear that when using `str.split()` the GC was being called before the method had finished running, this meant that the list and the values were being cleaned up prematurely. This PR adds in a mechanism to stop this happening while also fulfilling the original intent of adding escape codes.
=> Escape codes

c/value.c, c/vm.c, tests/operators/equality.du
Currently `bool([])` and `bool({})` give `true` back, and empty lists/dictionaries are falsey values. This is due to the `isFalsey` not checking for empty lists/dictionaries.
=> Add lists and dicts to falsey value check

c/vm.c, docs/docs/collections.md
Resolves #70 
Currently dictu does not have explicit checking to ensure that the object you are going to subscript on is actually an object, this is assumed. This is an issue because attempting to subscript on primitive types causes a segfault rather than a runtime error.
This PR introduces explicit checking for objects when attempting to subscript on an object and produce a viable runtime error if not. This PR also changes all user facing occurrences of "Array" to "List" to be consistent throughout.
=> Add additional check to ensure value is an object before subscripting

c/compiler.c
Resolves #44 
Currently the syntax for creating a dictionary is a `<left brace> + <string>` combination, however there are cases where this could produce a false positive, e.g:
```js
for (var i = 0; i < 10; ++i) {
"string";
}
```
This combination also does not allow dictionaries keys to be extended at a later date to other value types as the compiler is explicitly looking for a string token. Instead this PR advances the parser one token and checks for a colon, `<left brace> + <TOKEN> + <colon>`, and this is the basis for forming a dictionary. This means `<TOKEN>` can be of any type allowing the addition of more value types for dictionary keys, along with fixing the bug in the first code block.
=> Only create a dictionary if the advanced token is a colon

c/main.c
Resolves #74
This PR introduces multiline code blocks into the REPL. This is done based on the amount of opened and closed braces.
e.g
```
>>> print("hello");
'hello'
```
Opened and closed braces are equal (0), so this is treat as a single line.
```
>>> def test() {print("hello");}
```
Opened and closed braces are equal (1 for each), so this is treat as a single line.
```
>>> def test() {
...     print("hello");
... }
```
Opened and closed braces are **not** equal (1 open on the first line, none until closing function), so this is treat as a multiline until the braces are equal.
The REPL also has support for multiline strings (either single or double quotes). The concept is similar to the braces. If there is an unterminated string it will continue until the string is correctly terminated. …
=> Multiline REPL

c/datatypes/dicts.c
Resolves #79 
Currently .exists() for dictionaries does not take into account "deleted" entries. This PR changes the check to ensure a "deleted" value does not exist.
=> Fix issue with dict.exists()

c/value.c, c/vm.c, c/vm.h
Resolves #60 
Currently `FRAMES_MAX` is a constant (64), meaning, if we get a chain of functions "nesting" to 64 layers we will end up running into a runtime error saying we have overflowed the stack. This PR addresses this by growing the CallFrames within the VM as needed.
=> Grow CallFrames dynamically

c/vm.c, c/vm.h
Resolves #91 
If we have already imported a file, we do not want to run the entire import process again if another script ends up including the same file; instead we want to track the imported files and simply skip the process if we have already imported the file. Thats what this PR does by keeping an internal hashtable of imported files and skipping the import process if needs be.
=> Import cache

c/vm.c, docs/docs/classes.md, tests/classes/properties.du
Resolves #95
This PR adds in a new method on instances: `hasAttribute()`. This allows us to check at runtime whether an object has a given attribute or not.
e.g
```js
class Test {
init() {
this.x = 10;
}
}
var myObject = Test();
print(myObject.hasAttribute("x")); // true
print(myObject.hasAttribute("y")); // false
``` 
This PR also adds documentation about how attributes work within Dictu.
=> Attribute checking

c/datatypes/instance.c, c/datatypes/instance.h, c/vm.c, docs/docs/classes.md, tests/classes/properties.du
Resolves #97 
This PR adds two new instance methods `getAttribute` and `setAttribute`. These two methods allow attributes to be set / gathered from instances at runtime when the attribute is unknown.
Examples
```js
class Test {
init() {
this.x = 10;
}
}
var myObject = Test();
print(myObject.getAttribute("x")); // 10
print(myObject.getAttribute("x", 100)); // 10
print(myObject.getAttribute("y", 100)); // 100
print(myObject.getAttribute("y")); // nil
```
```js
class Test {
init() {
this.x = 10;
}
}
var myObject = Test();
myObject.setAttribute("x", 100);
print(myObject.x); // 100
```
=> Add getAttribute and hasAttribute

docs/docs/built-ins.md
Makes it so that the example functions on the built-in functions page are wrapped in code blocks.
=> Use code blocks in the example column.

c/compiler.c, c/compiler.h, c/memory.c, c/value.h, c/vm.c
- Add "repl" condition to compiler to decide OP_POP(_REPL) rather than in the VM
- Remove unnecessary expression() call
- Add prints back to debug GC trace
- Simplify `IS_BOOL` macro
- Fix instance call
=> Whole range of cleanup

c/linenoise.c, c/linenoise.h
Resolves #118 
This PR changes how tabs work within the REPL. Currently (as shown in the issue) linenoise doesn't seem to work with tabs very well, and seems to give weird behaviour. To counter this this PR converts tabs to 4 spaces and outputs those instead of the tab character.
=> Change tabs in the REPL to be 4 spaces

c/main.c, c/vm.c, c/vm.h
Resolves #121 
This PR moves when argv is defined from `interpret` to `initVM` as the argv was causing a segfault due to the GC.
=> Fix segfault when GC stress is enabled

c/memory.c, c/natives.c, c/object.c, c/object.h, c/optionals/env.c, c/optionals/env.h, c/optionals/math.c, c/optionals/optionals.h, c/value.h, c/vm.c, docs/docs/env.md, tests/env/env.du, tests/env/import.du, tests/maths/maths.du, tests/runTests.du
Currently when defining a native there is two routes a function can take, either `defineNative` or `defineNativeVoid` where the first returns a `Value` and the latter returns a Boolean. Instead this PR removes the need for this duplication and instead of returning and checking for errors on `NIL_VAL` there is a new `EMPTY_VAL` which has a sole purpose of error checking.
This PR also adds a new `Env` class which allows getting and setting of ENV vars.
=> Rework natives

c/value.c
Resolves #128 
The length being passed to snprintf for the "unknown" string is 7 and should be 8.
=> Fix snprintf length

c/datatypes/lists.c
In the list.join() method, some allocated memory was not being free'd as it should have been, this PR addresses this.
=> Fix memory leak in list.join()

c/optionals/system.c, c/optionals/system.h, docs/docs/system.md, tests/system/clock.du, tests/system/getCWD.du, tests/system/import.du, tests/system/time.du
Resolves #135 
This PR adds the ability to get the current working directory of the Dictu process. This PR adds a new method to the `System` native.
```
System.getcwd(); // '/path/here/to/a/directory'
```
=> Add System.getcwd()

c/optionals/system.c
This allows Dictu to build by the tcc (tinycc) compiler.
=> Silence tcc compiler and add a return statement to exitNative().

c/compiler.c, c/compiler.h
> The compiler adds a global variable’s name to the constant table as a string every time an identifier is encountered. It creates a new constant each time, even if that variable name is already in a previous slot in the constant table. That’s wasteful in cases where the same variable is referenced multiple times by the same function. That in turn increases the odds of filling up the constant table and running out of slots, since we only allow 256 constants in a single chunk.
=> Cache variables to avoid filling constants

c/datatypes/dicts.c, c/datatypes/instance.c, c/datatypes/lists.c, c/datatypes/sets.c, c/value.c, c/value.h, tests/benchmarks/list-methods/join.du
This PR fixes some pretty rare edge cases where values were being cleaned up by the GC prematurely. For example, if you `.insert()` on a literal list value (why would you in reality?), and you are at the point that the list needed to resize, this would cause the list to be cleaned up, as there is no reference to the list in variables, and it's not on the stack.
=> Garbage collection

c/datatypes/copy.c, c/datatypes/dicts.c, c/memory.c, c/memory.h, c/natives.c, c/object.c, c/object.h, c/optionals/http.c, c/optionals/json.c, c/table.c, c/value.c, c/value.h, c/vm.c
Currently the implementation if dicts in Dictu is duplicated. There is a Table type which is used internally, and there is a dict object which does the same thing - perform as a hash table. This PR removes the duplicated logic to instead use the present Table type which is used internally throughout the code base already - much like how lists work with ValueArrays.
=> Remove doubled "dict" logic as we can just use the Table type

c/compiler.c, c/vm.c
Since the 0.4.0 release there was an introduction of a new `stringConstants` table within the compiler. This is getting free'd in the `compile()` function however the table is being created and used in the `initCompiler` stage. `initCompiler` is used without necessarily calling `compile` (functions) meaning there is some memory not being free'd - This PR fixes that. It also fixes new native method tables not being free'd when the VM is cleaned up.
=> Correctly free new tables

c/memory.c, c/object.c, c/object.h, c/optionals/math.c, c/util.c, c/util.h, c/vm.c, docs/docs/math.md, tests/maths/maths.du
Resolves #170 
This PR adds the ability to add methods to native classes, the purpose of this change is to add the ability to define "constants" on respective classes. For example, this PR adds two new constants to the Math class, Pi, and e.
=> Add native class properties

c/optionals/http.h, c/optionals/system.c, c/optionals/system.h, c/vm.c, docs/docs/getting-started.md, docs/docs/system.md, tests/system/constants.du, tests/variables/import.du
This moves the magic `argv` variable into the System native class. This means it's behind a namespace and `argv` is now free to be used as a variable name.
=> Move argv magic variable into the System native class

c/optionals/system.c, c/vm.h, docs/docs/system.md, tests/system/setCWD.du
Mimic chdir() and libc conventions and return 0 uppon success or -1 otherwise.
Define those values as OK and NOTOK respectively in vm.h.
=> Do not raise an error in setCWD() if the operation is not successful.

c/memory.c, c/object.h, c/table.c, c/table.h, c/value.c, c/vm.c, tests/builtins/__file__.du, tests/dicts/remove.du
Resolves #172 
This PR changes the traditional linear scan used in hash tables within the Dictu interpreter to use the [Robin Hood](https://en.wikipedia.org/wiki/Hash_table#Robin_Hood_hashing) hashing collision scheme. Hash tables are such an important part of the VM that squeezing any amount of performance from them could have quite an impact.
I ran the tests 25,000 times, twice (with the exception of tests that take a while, e.g HTTP tests and System tests) to give a variety of different opcodes to try and give a fair benchmark for testing.
**Note: Results are in seconds**
|                              |Robin Hood|Generic Linear probe|
|-----------------|------------|---------------------|
|Maximum Time:  |0.02224      | 0.014499    |
|Minimum Time:   |0.005705              | 0.006219 …
=> Hash tables

c/datatypes/strings.c, c/datatypes/strings.h, docs/docs/strings.md, tests/strings/toNumber.du
`str.toNumber()` currently returns 0 on a failed parse, this means there real no way to check if a parse failed programmatically. This PR changes this by returning `nil` on a failed parse.
=> Failed toString parsing to return nil rather than 0

c/natives.c, docs/docs/collections.md, tests/sets/add.du, tests/sets/len.du, tests/sets/remove.du, tests/sets/toBool.du, tests/sets/toString.du
Currently a set has no way to be created with initial values leading to something like the following
```
var s = set();
s.add(1);
s.add(2);
s.add(3);
...
```
This PR changes this so any amount of arguments can be passed to set() and it will return a set with these values inside.
```
var s = set(1, 2, 3);
```
=> Allow set creation with values

c/datatypes/files.c, docs/docs/files.md, tests/files/import.du, tests/files/read.du, tests/files/read.txt, tests/files/readLine.du, tests/runTests.du
Currently `readLine()` returns an empty string when the file has finished reading, however there could just be an empty line within the file - this means there's no way to tell if it's finished reading or it's just a new line. This PR changes this to return `nil` when it has finished reading the file which gives a definitive value to check against for file completion.
This PR also fixes a bug where the string being created from `readLine()` had the wrong length and wasn't working correctly if the line did not include a new line character.
It also adds file reading into the test pipeline
=> Return nil when readLine() can read no more

c.make, c/chunk.c, c/compiler.c, c/datatypes/nil.c, c/main.c, c/natives.c, c/optionals/jsonParseLib.c, c/optionals/path.h, c/optionals/system.c, c/vm.h
This PR removes the `-Wno-unused-parameter` compiler flag and adds a new `UNUSED` macro. This will aid in development as it will force the developer to explicitly set a parameter to UNUSED when it is not being used.
=> Suppress the compiler warnings for unused parameters.

c/optionals/datetime.c, tests/datetime/strftime.du
Return an empty string when a zero length string is given as an argument. Use a maximum
iterator, to catch up some cases when strftime() returns an empty string in some locales.
=> Fix strftime() native method.

.github/workflows/main.yml, c/vm.c
When an import was importing another file, the pointer to the last module imported was not being reset, this means that the reference to the first import was wrong as it was referencing the second import. This PR fixes this by reseting the pointer to the last module when an import has finished.
Fix an issue with CI/CD process. cURL installation was failing without an update.
=> Reset the module to the function on import end

c/vm.c
Resolves #180 
At first look i thought the debug file was out of date as when tracing through the OPCODES the VM was running, it was obvious it was wrong. It turned out to be something else. The ip (instruction pointer, or program counter) was referencing `frame->ip` and not the local `ip` variable.
=> Point to the correct instruction pointer when disassembling

c/debug.c, c/object.c
Resolves #180 
This PR adds some missing opcodes to the disassembly function. This also fixes an issue where dictionary keys which were being converted to strings did not malloc enough memory in certain circumstances.
=> Add missing opcodes and fix issue with dicts

c/datatypes/dicts.c, docs/docs/collections.md, tests/dicts/import.du, tests/dicts/keys.du
This adds `.keys()` to dictionaries. This returns a list of all of the dictionary keys. This would be useful, for example, to loop through a dictionary.
=> Add dict.keys()

c/compiler.c, c/memory.c, c/object.c, c/object.h, c/vm.c, docs/docs/classes.md, tests/classes/classVariables.du, tests/classes/import.du
This PR adds the ability to define properties on the class itself rather than the instance. There is probably limited use case for this, however is a welcome addition nevertheless. Class variables in Dictu mimic functionality of class variables in Python, and can be seen as a "static" variable. They differ from instance variables in that they are defined on the class (as said above) rather than the instance, therefore this means all instances share this value.
```js
class Test {
var x = 10; // Class variable
init() {
this.val = 1; // Instance variable
}
}
var x = Test();
var y = Test();
print(x.x); // 10
print(y.x); // 10
Test.x = 10000; // Update class variable
print(x.x); // 10000
print(y.x); // 10000
```
=> Add the ability to define class variables

.gitignore, c/memory.c, c/natives.c, c/object.c, c/object.h, c/optionals/c.c, c/optionals/datetime.c, c/optionals/env.c, c/optionals/http.c, c/optionals/json.c, c/optionals/math.c, c/optionals/optionals.h, c/optionals/path.c, c/optionals/system.c, c/vm.c, tests/builtins/type.du
Currently within the internals of Dictu, there is an object for "native classes" and objects for "modules". "native classes" currently house the Stdlib, for example, `System` or `JSON` for example, and "modules" are used when importing Dictu code, however they both achieve the same effect which is to namespace like code. Both of them are not required so this removes "native classes" in favour of "modules". This will simplify the Dictu internals a lot, and will eventually lead to the ability to import "native classes" rather than having them injected into the VM at runtime.
=> Remove "native classes" in favour of modules

c/compiler.c, c/vm.c, tests/classes/import.du, tests/classes/parameters.du
Resolves #243 
Currently within the VM, the `DEFINE_OPTIONAL` opcode is basing it's logic on the fact that the thing being called is a closure, which may not always be the case, and may for example be an instance. In that case the default parameters are not working as expected. This PR changes this to instead base it off the function (methods) arg count and arity resolving this issue.
=> Parameters

c/compiler.c, c/scanner.c, tests/maths/maths.du, tests/number/toBool.du, tests/number/toString.du
Implements the feature as in #271 .
Added relevant tests, and checked for leaks and such.
Note: The underscore can only occur in the non fractional part of a number, this was an intentional choice. If you want me to modify it so that it can appear even in the fractional part I will happily implement that.
=> Add support for `_` as a delimiter in numbers.

c/vm.c
Resolves #238 
This PR resolves the issue with importing. Currently when an import happens a closure object is created however it is not pushed onto the stack. When the closure is called the vm frames may need to grow in capacity which in turn could therefore trigger a GC. We need to make sure the closure is not lost to the GC.
=> Fix import issue

.github/workflows/main.yml, CMakeLists.txt, README.md, docs/index.md, tests/system/setCWD.du
Resolves #289 
Resolves #284 
Resolves #283
This PR updates Github Actions to also run the test suite on windows OSs. Along with this, it fixes an issue where the interpreter could not be built on Ubuntu 20 by turning on CMake extensions. Lastly it updates the build instructions to include some CMake variants for anyone wishing to generate build files for Dictu with CMake.
=> Add windows to Github Actions

c/common.h, c/memory.h, c/optionals/http.c, c/optionals/http.h, c/table.c, c/value.c, c/vm.h
Resolves #254 
Upon testing it was found that the internal string table was being resized as part of a GC and ended up in a loop / freeing strings which should not have been free'd. This PR resolves this issue by not scaling tables down and therefore stopping the looping however it's not the fix i was looking for as this means tables could be massively oversized using more memory than necessary. This PR also fixes a few issues with the HTTP lib where the cleanups were not running where they should have been.
- Although this PR does fix the issue, it introduces an issue where tables do not scale down and therefore introduces the potential of memory waste, worth looking into a resolution to this new issue.
=> Fix an issue where multiple calls to the HTTP lib would segfault

c/optionals/datetime.h, c/optionals/http.c
Resolves #308 
This PR adds in some preprocessor conditionals around definitions as it seems they've already been defined in some scenarios while also changing the function header of `writeData` back to what it was.
=> Allow dictu to compile on alpine linux

c/compiler.c
Abstract methods are methods defined in abstract classes that have no implementation and **must** be defined in classes which inherit the base class. Currently if a user creates a base class, and does actually provide an implementation in the abstract class, which is not allowed, the error message is a bit confusing (`Error at '{': Expect method name.`). This PR changes the error message to instead be `Error at ')': Abstract methods can not have an implementation.`.
=> Abstract method error

c/compiler.c, c/datatypes/files.c, c/datatypes/lists.c, c/datatypes/number.c, c/datatypes/strings.c, c/natives.c, c/optionals/datetime.c, c/optionals/http.c, c/optionals/json.c
Recently there was an update where many calls to `copyString` were changed to `takeString` which on the surface made sense, however on further thinking, it wasn't right. If we used takeString and a given string was already interned then you would be left with allocated memory hanging around (since the GC would not clean allocated char pointers). This PR changes this to go back to using copyString and properly cleaning the allocated strings.
=> Update use of takeString

.gitignore, src/optionals/windowsapi.h
When attempting to build Dictu on windows 8 with CLion and mingw-w64 the value for `_WIN32_WINNT` was `0x502` which corresponds to windows server 2003. `inet_ntop` was added as part of Windows Vista, so to work around this faulty value we ensure the macros value is set to at least `0x0600` which corresponds to Windows Vista.
=> Ensure inet_ntop is included

src/optionals/socket.c, src/vm/memory.c, src/vm/natives.c, src/vm/object.c, src/vm/object.h, src/vm/value.h, src/vm/vm.c, tests/sockets/bind.du, tests/sockets/create.du, tests/sockets/setsockopt.du
This adds a new type of object to the internals of Dictu, `OBJ_ABSTRACT`. What this is, is essentially a wrapper for any type of data that a C extension could possibly need (for example the socket library needs a struct of data to store information about socket data). The benefit of this type is it allows a much easier interface when creating C extensions as the new type does not need to be added throughout the internals of the VM and instead everything can be encapsulated within the additional files!
The GC will handle freeing the majority of the abstract object, however all user created mallocs within the given extension must be free'd, to do this is quite simple.
When we create the new abstract object it expects two parameters, the VM, and a function pointer
```c
typedef void …
```
=> Internal abstract type

src/vm/compiler.c, tests/operators/plus.du
This PR fixes an issue with constant folding where it was wrongly attempting to fold a method call when the left operand was a call to a superclass method.
=> Fix an issue with constant folding

docs/docs/collections/dictionaries.md, src/vm/vm.c, tests/dicts/subscript.du
Resolves #343 
This PR changes dictionary subscription behaviour. Currently if you subscript on a dictionary and the key is not present `nil` would be returned. This PR changes this so instead a runtime error occurs. The reasoning behind this change is it makes the code a lot more explicit in an erroneous situation rather than attempting to carry on with a `nil` value. It should also prod the programming to handle a `nil` case more often.
=> Dictionary Subscription

docs/docs/collections/lists.md, src/vm/datatypes/lists/lists.c, tests/lists/join.du
This PR fixes an issue where attempting to use `list.join()` on an empty list would produce a segfault. This PR handles this correctly, and instead will return an empty string when using `.join()` on an empty list.
=> List.join()

docs/docs/standard-lib/sockets.md, src/optionals/socket.c, src/vm/util.c
This PR adds a new `socket.connect` method, along with some bug fixes. Previously there was no way to connect to a socket, only bind to an address, this PR changes this.
This PR also includes bugfixes for `socket.recv` where the total memory was incorrectly being reported, and a bugfix for resolvePath (Thanks @agathoklisx).
=> Socket connect

src/optionals/sqlite.c, tests/sqlite/create.du
Previously when a SQLite connection was being cleaned up by the garbage collector, or if `.close()` was called multiple times `sqlite_close()` was being ran regardless of whether or not a previous connection had already been free'd. This PR changes this by tracking the open status of the SQLite object.
=> Correctly track sqlite database status

src/vm/compiler.c
The comparison as to whether the string length had changed due to escape chars was off by 1, this PR resolves this. This was not causing any issues other than the fact it was always resizing the buffer when in most cases it didn't need to.
=> Correctly handle string resizing when dealing with escape chars

.github/workflows/main.yml, src/CMakeLists.txt
Since a change in versions for the MSVC compiler on actions compilation was failing ([example](https://github.com/dictu-lang/Dictu/pull/330/checks?check_run_id=1424824631)). This PR gets compilation working on actions again for windows versions.
=> Get windows CI/CD working again

src/cli/argparse.c, src/cli/argparse.h, src/cli/main.c, src/optionals/system.c
This adds in argument parsing for the CLI. Currently the CLI only has support for the REPL and executing a file with limited customisability, this PR instead implements a [dedicated argument parsing library](https://github.com/cofyc/argparse) along with a couple of new options.
`dictu --help` output
```
Usage: dictu [options] [[--] args]
or: dictu [options]
-h, --help        Show this help message and exit
-v, --version     Display Dictu version
-c, --cmd=<str>   Run program passed in as string
```
=> Argument parsing

src/optionals/http.c
# HTTP
In a scenario where a webserver would send no content back a segfault would occur when attempting to generate the content as a `Value` as it would be NULL. This PR resolves this by checking for null and returning an empty string if `writeResponse` is never called.
=> Handle scenario where webserver sends no response back correctly

docs/_includes/css/just-the-docs.scss.liquid, docs/_includes/head.html, docs/_sass/color_schemes/dictu.scss, docs/_sass/content.scss, docs/_sass/custom/custom.scss
Currently the light / dark mode of the documentation website is currently being determined by JS, this means on page load it can sometimes cause a flicker while it transitions to the dark theme - this PR resolves this by correctly handling it through media queries in the CSS rather than through JS.
=> Dark / light mode based on CSS rather than JS

docs/docs/classes.md, docs/docs/error-handling.md, src/vm/datatypes/generate.du, src/vm/datatypes/result/result-source.h, src/vm/datatypes/result/result.c, src/vm/datatypes/result/result.du, src/vm/datatypes/result/result.h, src/vm/value.c, src/vm/vm.c, tests/result/import.du, tests/result/match.du, tests/result/unwrap.du, tests/runTests.du
This PR adds a new `Result.match()` method. This method takes two callbacks, one that runs when the result value is of type SUCCESS and the other on ERROR. The callback takes 1 parameter as is passed either the value of `unwrap()` or `unwrapError()` respectively.
This PR also handles result value types when calling `type()`.
```js
var number = "10".toNumber().match(
def (result) => result,
def (error) => {
print(error);
System.exit(1);
}
);
print(number); // 10
```
=> Result.match()

docs/docs/error-handling.md, src/vm/datatypes/strings.c, tests/result/match.du, tests/strings/toNumber.du
This PR updates the error message for `toNumber()` from "Can not convert 'number' to number" to "Can not convert '<string>' to number". This should give a much clearer reason for the conversion failure as you can see the attempted string.
=> toNumber error message

src/vm/compiler.c
This PR changes the constants table to be free'd after a call to `compile()`. Currently the table would not be free'd until the VM is cleaned up, however it doesn't need to live that long. It also means we don't need to handle the case where variables in other modules which share names would need to be removed from the table.
=> Free the constants table when done compiling

src/optionals/http.c, tests/http/get.du
This sets up both GET and POST requests to accept GZIP responses.
=> Accept GZIP compressed responses

docs/docs/collections/lists.md, src/vm/compiler.c, src/vm/datatypes/lists/list-source.h, src/vm/datatypes/lists/list.du, src/vm/vm.c, tests/lists/forEach.du, tests/lists/import.du
This PR adds a new `.forEach()` builtin method to lists. Similar to map in that it allows a callback function to be ran for each element within a list however differs in the fact that it doesn't return anything.
=> List.forEach()

src/vm/compiler.c, src/vm/compiler.h
Previously when assigning a constant and capturing it as part of a closure the constant could actually be changed as there was no validation on the `SET_UPVALUE` opcode. This PR changes this to ensure constants can't be changed even if captured as part of a closure.
=> Handle constant upvalues correctly

src/vm/datatypes/strings.c
Resolves #384 
This corrects the indexes used when validating the arguments passed to `str.replace()`
=> Correct indexes for str.replace value type validation

docs/docs/collections/lists.md, src/vm/datatypes/lists/list-source.h, src/vm/datatypes/lists/list.du, tests/lists/find.du, tests/lists/forEach.du, tests/lists/import.du
This PR adds `list.find()` to Dictu. `.find()` will search through the array and apply a callback function to each element, if the callback returns a truthy value then the item from the list that satisfied the callback is returned.
=> Add list.find()

docs/docs/collections/lists.md, src/vm/datatypes/lists/lists.c, tests/lists/import.du, tests/lists/reverse.du
This adds a built-in `.reverse()` method to lists which (as the name suggests) reverses a list.
Note: This reverses a list in-place, if you do not wish to modify the original list make a copy first.
=> Add built-in method to reverse a list

src/vm/compiler.c, src/vm/compiler.h, src/vm/debug.c, src/vm/vm.c
Resolves #391 
Previously a file would not be closed correctly if we exited from the with scope with a return statement, this left dangling file handlers lying around. This PR resolves this by emitting `OP_FILE_CLOSE` if a return statement is used in a `with` block.
This PR also fixes an issue where `file` in a with block could be declared as a new variable / constant - this has been fixed so now `file` is reserved within a with block.
=> Handle closing file if exiting scope early with return

src/vm/compiler.c, src/vm/datatypes/files.c
#392 fixed an issue with file descriptors not being closed when exiting from a with scope early, however, it introduced an issue where it was actually closing the file handle **before** evaluating the return statement, this meant if you were returning an expression that included something to do with the file, it would not work correctly. This PR resolves that issue.
=> Send the opcode to close files AFTER the return expression

src/vm/object.c
The logic was checking if the element size was greater than 2 times the current allocated memory length when it should have been just the allocated length (since it's getting doubled). It also didn't account for quotes added around string values and the null terminator.
=> Fix issue where list to string resizing wasn't correct

README.md, examples/README.md, examples/bubbleSort.du, examples/classes.du, examples/guessingGame.du, examples/inheritance.du, examples/isPalindrome.du, src/vm/compiler.c, src/vm/vm.c
This PR fixes a slight issue where constants defined within the REPL could be re-assigned along with updating the example Dictu programs to bring them more in-line with what they should be.
=> Update examples and correctly handle constants for the repl

src/vm/natives.c, tests/http/get.du, tests/http/post.du
`isDefined` was only checking the globals table stored in the VM which is only used for a handful of builtin functions. This meant we couldn't check for things such as if the HTTP module has been compiled correctly (and therefore the tests were also not running). This PR fixes this so that it checks global scope at a module level, globals table and the list of builtin modules.
=> Correctly handle isDefined

Docker/DictuAlpineDockerfile, Docker/DictuUbuntuDockerfile, src/optionals/process.c
This PR updates the dockerfiles to pull from git rather than rely on the source being locally available already. This means services such as dockerhub can be used to build images. It also fixes an issue where the return of pipe wasn't being used.
=> Update dockerfiles to pull from git instead of local

src/vm/compiler.c, src/vm/error_lib/LICENSE, src/vm/error_lib/README.md, src/vm/error_lib/error.c, src/vm/error_lib/error.h, src/vm/error_lib/term.c, src/vm/error_lib/term.h, src/vm/vm.c
This PR updates the error reporting to add a little bit of colour (non-windows) along with the option to further extend error reporting. It also changes the error warning for the `+` operator from `"Unsupported operand types for +: 10, 'test'"` to `Unsupported operand types for +: 'number', 'string'`.
The system to handle different formatting and colours was taken from [this](https://github.com/cometodukey/tbd) repository, thanks @cometodukey!
=> Error reporting

src/vm/object.c
When printing methods which are bound to a class, it is incorrectly printing static as bound methods and bound methods as static methods.
```
class Test {
init() {
print(this.func); // <Static Method func>
print(this.func1); // <Bound Method func1>
}
func() {}
static func1() {}
}
Test();
```
This PR resolves this.
=> Fix printing bound methods

docs/docs/collections/dictionaries.md, src/vm/datatypes/dicts/dict-source.h, src/vm/datatypes/dicts/dict.du, src/vm/datatypes/dicts/dicts.c, src/vm/datatypes/dicts/dicts.h, src/vm/datatypes/generate.du, src/vm/vm.c, tests/dicts/forEach.du, tests/dicts/import.du
Resolves #412 
This PR adds in `dict.forEach` which makes iterating over a dictionary much nicer. As explained in the issue we would have to iterate over a list of keys and then index back into the dictionary which is a nit nasty.
=> dict.forEach()

docs/docs/built-ins.md, src/vm/natives.c, src/vm/value.c, src/vm/value.h
This PR adds a new `printError()` builtin that is functionally the same as `print()` however it's stream is `stderr` rather than `stdout`.
=> printError

docs/docs/strings.md, src/vm/datatypes/strings.c, tests/strings/title.du
Added New Feature: String utility method called title(), for return a title cased string. 
The title() method returns a string with first letter of each word capitalized; a title cased string.
Updated Docs , and tests are ran successfully .
=> Added string.title() method to return a title cased string

.github/workflows/main.yml
Updated the github workflow to remove Ubuntu v16 which is now EOL and add in MacOS version 11 (big sur) as macos-latest is still pointing to catalina.
#
Change is required as thee ubuntu 16 pipeline is queued indefinitely.
#
#
=> Remove ubuntu 16 from the workflow and add macos11

src/optionals/path.c, tests/path/import.du, tests/path/join.du
The tests weren't running for `Path.join` previously, so a small memory issue slipped in. This PR makes the `Path.join` tests run, and fixes that bug.
=> Fix memory issue with `Path.join`

src/optionals/path.c, tests/path/join.du
Previously this was the behaviour of `Path.join` with leading directory separators:
```
>>> Path.join('/tmp/', '/abcd/', '/efg/');
/tmp//abcd//efg
```
Now this is the behaviour:
```
>>> Path.join('/tmp/', '/abcd/', '/efg/');
/tmp/abcd/efg
```
=> Strip leading dir separators in `Path.join`

docs/docs/collections/lists.md, src/vm/datatypes/lists/list-source.h, src/vm/datatypes/lists/list.du, tests/lists/find.du, tests/lists/findIndex.du, tests/lists/import.du
This PR adds a new method to lists, `list.findIndex()`. It works almost exactly the same as the current `list.find()` except that instead of returning the value from within the list it returns the index at which the item was found within the list.
This PR also extends `list.find()` to have 2 new optional parameters, start and end, which allow us to restrict the items we are searching through the list.
=> list.findIndex()

src/vm/datatypes/instance.c
This PR changes `obj.getAttribute` so that a bound method is returned rather than a function. This will allow us to pull methods off of a class, store in a variable, and call it later as though we were doing it through the object.
#
=> obj.getAttribute to return bound method rather than function

src/vm/datatypes/class.c, src/vm/datatypes/instance.c
This PR fixes an issue where the loop for `.methods()` is off by one.
#
=> Off by one error for methods() method

docs/docs/classes.md, src/vm/object.c, tests/classes/properties.du
This PR adds a new `_class` attribute to all instances when they are created. This will give reference to the class which the object was instantiated from. This will be useful for a number of cases, but one of them being it gives us a way to pull class attributes from an object.
#
=> Add _class attribute to instances

docs/docs/strings.md, src/vm/datatypes/strings.c, tests/strings/split.du
This PR adds a new optional argument to `str.split()` which determines the amount of times a string will actually be broken up by the delimiter. This allows us to keep the delimiter within the string after a certain amount of occurrences have already been found.
E.g
```
"Dictu is awesome!".split(" ", 0); // ['Dictu is awesome!']
"Dictu is awesome!".split(" ", 1); // ['Dictu', 'is awesome!']
"Dictu is awesome!".split(" ", 2); // ['Dictu', 'is', 'awesome!']
```
#
This may come in useful with regards to #473
=> Add optional argument to split

examples/runExamples.du, examples/structured_logger.du
Adds a simple JSON structured logger.
Resolves: #
#
#
#
=> add structured logger example app

examples/runExamples.du, examples/template_engine.du
Adds a very naive template engine to show off use of `getAttributes`.
Resolves: #
#
#
#
=> add template engine example app

docs/docs/classes.md, src/vm/compiler.c, src/vm/datatypes/instance.c, src/vm/memory.c, src/vm/object.c, src/vm/object.h, src/vm/vm.c, tests/classes/classConstants.du, tests/classes/import.du
This PR adds the ability to define a constant within a class. This comes with the runtime guarantee that the value will not be changed.
E.g
```
class SomeClass {
const classVariable = 10; // This will be shared among all "SomeClass" instances
init() {
this.x = 10; // "x" is set on the instance
}
}
print(SomeClass.classVariable); // 10
const x = SomeClass();
const y = SomeClass();
print(x.classVariable); // 10
print(y.classVariable); // 10
SomeClass.classVaraible = 100; // Cannot assign to class constant 'SomeClass.classVariable'.
```
Resolves: #
#508 
#
#
=> Class constants

docs/docs/standard-lib/unittest.md, src/optionals/http/http-source.h, src/optionals/unittest/unittest-source.h, src/optionals/unittest/unittest.du
This PR moves the results to be stored within the test object itself rather than stored on the parent UnitTest class. It also adds two new global flags `forceExitOnFailure` and `forceOnlyFailures`. These are class variables on UnitTest that can be set meaning they do not need to be set on every single unittest class.
The previous attributes still work and allow class level filtering too.
#
#
=> UnitTest flags

src/vm/compiler.c
Correctly set the VM reference to the last module after an import has comlpeted
=> Correctly reset last module after import statement

docs/docs/standard-lib/unittest.md, src/optionals/unittest/unittest-source.h, src/optionals/unittest/unittest.du
Adds a new helper `assertType(x, y)` which is the same as `assertEquals(type(x), y);`
Also fixes a bug where `assertNotEquals` had the wrong comparison check.
=> Add assertType method to UnitTest

src/vm/compiler.c
This PR changes `OP_POP_REPL` to only print when in the top level. This will stop things like expressions in functions being printed to the REPL and instead just handle things like function returns.
Resolves: #529 
#
#
=> OP_POP_REPL

docs/docs/classes.md, src/vm/object.c, tests/classes/properties.du
Adds a new attribute `_name` to classes that returns the string representation of their name
Resolves: #540 
#
#
#
=> Add _name attribute

src/vm/vm.c
While Importing the same file as a module in the same file we are getting a Segmentation fault.
Ex: if we execute the below code by writing it in test.du file
`import "./test.du";
var x = 1;
print(x);`
Resolves: #
After creating the module we need to add it to vm->modules table to keep it tracked.
#
added below line in vm.c file in IMPORT opcode block
`tableSet(vm, &vm->modules, fileName, OBJ_VAL(module));`
#
#
Before changes
After Change
=> Fixed self import Segmentation fault

src/vm/object.c
updated listToString and dictToString functions inorder to skip segfault
```
// for list
var x = [1,2,3];
x.push(x);
print(x);// [1,2,3,[...]
```
```
// for dict
var a ={1:2};
a[2]=a;
print(a);// {2: {...}, 1: 2}
```
Resolves: #
Self referencing datatypes #354
#
#
#
=> Fixed self referencing datatypes bug

src/cli/main.c
Resolves an issue where the argparse library used was erroring at an unknown argument, instead we pass a flag to stop argparse at an unknown command.
Resolves: #561
#
#
#
=> Stop at non-option argparse

docs/docs/standard-lib/system.md, examples/copyFile.du, src/optionals/system.c, tests/system/copyFile.du, tests/system/import.du
Adds a convenience function to copy the bytes from one file to another.
Resolves: #
#
#
#
=> add copyFile func

docs/docs/files.md, src/vm/datatypes/files.c, tests/files/readLine.du
Adds optional arg to readline for the size buffer to use.
Resolves: #
#
#
#
=> add optional arg to readline for buffer size

.github/workflows/main.yml, README.md, src/cli/CMakeLists.txt, src/cli/main.c
Removed DISABLE_LINENOISE macro and relevant code.
#
#
=> Removed option to build without linenoise (depends on #597)

src/cli/main.c
This corrects multiline statements in the REPL in 2 ways:
1) The combined multiline string is now always null-terminated - for example, copying the contents of fibonacci.du would previously cause an 'Unexpected character' error.
2) The lines have newlines separating them, so the error messages show the line number of the error. The following error would previously show line 1 for everything.
```
>>> {
... {
... 'a'
... }
... }
Error: File 'repl', line 4
4 | }
Expect ';' after expression.
Error: File 'repl', line 5
Error at end: Expect '}' after block.
Error: File 'repl', line 5
Error at end: Expect '}' after block.
```
The string literal and brace matching code was also changed to act more like the way a parser would do it.
#
=> REPL fixes (depends on #598)

.github/workflows/release.yml
Adds the ability to push a new image up to Dockerhub whenever a new release is created.
New secrets will need to be added:
DOCKERHUB_USERNAME
DOCKERHUB_TOKEN
Resolves: #
#404 
#
#
=> Add docker build and push to release actions

src/vm/compiler.c
Correctly close upvalues after use of `break` and `continue` statements.
Resolves: #608
=> Close upvalues after `continue` and `break` statements

src/vm/compiler.c, src/vm/compiler.h, src/vm/scanner.c, src/vm/scanner.h
Renamed Token to LangToken, and TokenType to LangTokenType to avoid Win API nameclashes when compiling with HTTP module support.
Resolves: #616
#
#
#
=> Renamed tokens to avoid windows nameclash

docs/docs/standard-lib/argparse.md
Fixed a typo on the Argparse documentation, where it was importing `Parse` instead of `Parser`
Resolves: #
#
#
#
=> fix typo on  Parser import

src/optionals/c.c, src/optionals/c.h, src/optionals/optionals.c, src/optionals/optionals.h, src/vm/vm.c
Resolves: #637 
Updated the code to require the C module to be loaded like all other modules and not be autoloaded with the VM.
#
#
#
=> un-auto load C module

docs/docs/error-handling.md, src/vm/datatypes/result/result-source.h, src/vm/datatypes/result/result.du
A helper similar to match that will automatically return the value wrapped in a success Result type. Helpful as most of the time we simply want to just unwrap a Result without actually transforming it inbetween
#
#
#
=> Add new matchError helper

docs/docs/collections/lists.md, src/vm/datatypes/lists/list-source.h, src/vm/datatypes/lists/list.du, tests/lists/import.du, tests/lists/uniq.du, tests/lists/unique.du
Add the ability to deduplicate a list.
#
#
=> Add uniq method to list type

src/optionals/system.c
EOF is defined as -1 so when comparing against a `char`(!= in copyFile) it's always going to be true
#
#
#
=> Correct type

src/optionals/queue.c, src/optionals/stack.c, src/vm/memory.c, src/vm/object.c, src/vm/object.h, tests/queue/queue.du, tests/stack/stack.du
Fixes an issue where abstracts couldn't grey any values they kept track of. This PR now allows us to add a grayValue function to abstracts that can run and take care of any values that they keep track of.
It also fixes a couple of issues with the stack and queue modules
#
#
#
=> Fix issue with abstracts not being able to grey

docs/docs/standard-lib/sqlite.md, src/optionals/sqlite.c
Resolves: #667 
Adds the ability to set SQLite timeout. Currently if the database is locked it will immediately fail, instead we introduce a default timeout of 5 seconds
#
#
#
=> Sqlite timeout

docs/docs/collections/lists.md, src/vm/datatypes/lists/lists.c, tests/lists/sort.du
Resolves: #636 
Nothing modified, or breaking changes. Sort functionality is now extended to sort the list of strings also. 
(not supports heterotypic lists).
#
- [ x] New feature
#
- [x ] Tests have been updated to reflect the changes done within this PR (if applicable).
- [ x] Documentation has been updated to reflect the changes done within this PR (if applicable).
#
=> [Feature] Extending sorting functionality for list with string elements

docs/docs/enum.md, src/vm/compiler.c, src/vm/datatypes/enums.c, src/vm/datatypes/enums.h, src/vm/memory.c, src/vm/vm.c, src/vm/vm.h, tests/enum/enum.du
Resolves: #658 
Add new Enum.values() method
Allow trailing comma in Enum declarations
#
#
#
=> Add new Enum.values() method

docs/docs/standard-lib/io.md, docs/docs/standard-lib/json.md, docs/docs/standard-lib/log.md, docs/docs/standard-lib/math.md, docs/docs/standard-lib/object.md, docs/docs/standard-lib/path.md, docs/docs/standard-lib/process.md, docs/docs/standard-lib/queue.md, docs/docs/standard-lib/random.md, docs/docs/standard-lib/socket.md, docs/docs/standard-lib/sqlite.md, docs/docs/standard-lib/stack.md, docs/docs/standard-lib/system.md, docs/docs/standard-lib/term.md, docs/docs/standard-lib/unittest.md, docs/docs/standard-lib/uuid.md, examples/io.du, src/optionals/io.c, src/optionals/io.h, src/optionals/optionals.c, src/optionals/optionals.h
Resolves: #679 
Adds a new module called IO that contains 2 functions. `print` prints the given input, and `println` prints the given input but adds a newline character.
#
#
=> add IO module

docs/docs/standard-lib/json.md, docs/docs/standard-lib/path.md, docs/docs/standard-lib/process.md, docs/docs/standard-lib/sqlite.md, docs/docs/standard-lib/system.md, docs/docs/standard-lib/uuid.md
Fix the wrapped value not showing
#
#
#
=> Fix the wrapped value not showing

docs/docs/standard-lib/net.md, docs/docs/standard-lib/object.md, docs/docs/standard-lib/path.md, docs/docs/standard-lib/process.md, docs/docs/standard-lib/queue.md, docs/docs/standard-lib/random.md, docs/docs/standard-lib/socket.md, docs/docs/standard-lib/sqlite.md, docs/docs/standard-lib/stack.md, docs/docs/standard-lib/system.md, docs/docs/standard-lib/term.md, docs/docs/standard-lib/unittest.md, docs/docs/standard-lib/uuid.md, examples/ip.du, src/optionals/net.c, src/optionals/net.h, src/optionals/optionals.c, src/optionals/optionals.h, tests/net/import.du, tests/net/parseIp4.du, tests/runTests.du
Adds a new module called "Net" with a couple constants, and functions.
I was imagining the next iteration of this to be to move the Socket module into this module, in some capacity.
#
#
#
=> Add net module, tests, and docs

src/optionals/http/http.c, src/optionals/http/http.h
Resolves: #666
There wasn't actually an issue with the memory, just an issue with the count if the write function was called many times (larger HTTP responses). It was adding 1 to the count for the null terminator and not excluding that from the count on subsequent requests
#
#
#
=> Correct memory count

src/vm/vm.c
Resolves: #709
Removed numeric value from error message and created a single macro to use in the few cases.
#
#
=> Resolve typo and use single macro

src/vm/vm.c
The string was being popped off the VM before the call to copyString, this meant the string was getting free'd and then the value was attempted to be used.
#
#
#
=> Fix issue where string was getting popped before created

src/cli/main.c
Check errno for `EEXIST` and ignore if so.
#
#
=> account for history existing

src/cli/main.c
Resolves: #718 
The path string was being freed after the first statement had been executed, meaning further statements in the REPL was using a freed string 
#
#
#
=> Dont free path after first execution

docs/docs/strings.md, src/vm/datatypes/strings.c, tests/strings/findLast.du, tests/strings/import.du, tests/strings/lastIndexOf.du
Add lastIndexOf string method to find the last index of a given string in another string.
#
#
=> add findLast string method

docs/docs/collections/sets.md, src/vm/datatypes/sets.c, tests/sets/import.du, tests/sets/values.du
Adds a native function to retrieve a list of all values within a set.
#
#
=> feat: set.values()

src/vm/datatypes/dicts/dicts.c, src/vm/object.c, src/vm/object.h, src/vm/value.c
The dict findDictEntry function did not correctly handle the case when, a dict had no "free" slot but had tombstones, it would loop forever.
Resolves: https://github.com/dictu-lang/Dictu/issues/726
This fixes that by conditionally returning a tombstone when all other indexes where processed.
#
=> fix: correctly return tombstone when theres no free element

docs/docs/collections/lists.md, src/vm/datatypes/lists/list-source.h, src/vm/datatypes/lists/list.du, tests/lists/import.du, tests/lists/sortFunc.du
Adds a function to list implemented in dictu which uses quickSort to allow custom sorting which is suuuper useful for a lot of problems. I would have preferred to implement this is C too but there doesn't seam to be a straight forward way to pass callbacks into c. Using a hybrid approach would have been hacky too, but of course this approach does duplicate the sorting logic.
#
=> feat: add list.sortFunc

docs/docs/collections/dictionaries.md, src/vm/datatypes/dicts/dict-source.h, src/vm/datatypes/dicts/dict.du, tests/dicts/import.du, tests/dicts/toObj.du
Adds a method to the dictionary type that receives a class ref and populates it with the contents of the dict it was called from.
#
#
=> add dict.toObj(Object) method

docs/docs/standard-lib/path.md, src/optionals/path.c, tests/path/import.du, tests/path/isSymbolicLink.du
Theres a issue where isDir is checked on a broken symbolic link, it will return true falsely.
This adds checks for the return value of isDir and also adds a new function called `isSymbolicLink` which checks if a file is a symbolicLink
#
#
#
=> feat: isSymbolicLink

src/optionals/process.c
Trying to waitpid before reading the piped content will lead to a blocked pipe and get the child process "stuck". So it should be read BEFORE waitpid is called. Further there was a bug within the reallocation logic leading to heap corruption because the comparison size did not include the just read chunk, leading to heap corruption, which itself led to reallocate failing.
#
=> fix: when executing a child process, do not waitpid before reading

docs/docs/files.md, ops/checkTests.du, src/vm/compiler.c, src/vm/compiler.h, src/vm/vm.c, tests/files/read.du, tests/files/read2.txt, tests/files/write.du
This refactors the logic in the compiler to allow files to have
custom variable names and also allow the nesting of multiple files
within each other. Both of which should be possible.
The latter is a bit questionable in terms of code quality but needed anyways.
#
#
#
=> feat: allow custom var name for with statement and nesting of files.
